


import {
    TEXT_COLOR_VAR,
    NEGTIVE_TEXT_COLOR_VAR,
    ACTIVE_TEXT_COLOR_VAR,
    DISABLED_COLOR_VAR,
    HIGHTLIGHT_COLOR_VAR,
    BACKGROUND_0_VAR,
    BACKGROUND_1_VAR,
    BACKGROUND_2_VAR,
    BACKGROUND_3_VAR,
    BACKGROUND_4_VAR,
    BACKGROUND_5_VAR,
    BACKGROUND_6_VAR,
    BOARDER_COLOR_VAR,
    PRIMARY_BACKGROUND_VAR,
    HIGHLIGHT_BACKGROUND_VAR,
    CANVAS_MASK_BACKGROUND_VAR,
    HIGHLIGHT_BORDER_COLOR_VAR,
    HEAD_HEIGHT,
    ASIDE_WIDTH,
    PANEL_WIDTH,
    PADDING_1_VAR,
    PADDING_2_VAR,
    PADDING_3_VAR,
    PADDING_4_VAR,
    PADDING_5_VAR,
    PADDING_6_VAR,
    PADDING_7_VAR,
    PADDING_8_VAR,
    PADDING_9_VAR,
    HIGHTLIGHT_TEXT_COLOR_VAR,
    LINE_1_VAR,
    LINE_2_VAR,
    MOVABLE_MASK_BACKGROUND_VAR
} from './constant'

// export const TEXT_COLOR = '#83868E'
// export const ACTIVE_TEXT_COLOR = '#EFEFF0'
// export const BACKGROUND_1 = '#1A2233'
// export const BACKGROUND_2 = '#242C38'
// export const BACKGROUND_3 = '#2A3141'
// export const BACKGROUND_4 = '#333B4E'



// export default {
//     [TEXT_COLOR_VAR]:'#83868E',
//     [ACTIVE_TEXT_COLOR_VAR]:'#EFEFF0',
//     [HIGHTLIGHT_COLOR_VAR]:'#ffb364',
//     [HIGHTLIGHT_TEXT_COLOR_VAR]:'#4e4f50',

//     [BACKGROUND_0_VAR]:'#090a0a',
//     [BACKGROUND_1_VAR]:'#1A2233',
//     [BACKGROUND_2_VAR]:'#242C38',
//     [BACKGROUND_3_VAR]:'#2A3141',
//     [BACKGROUND_4_VAR]:'#333B4E',
//     [BACKGROUND_5_VAR]:'#525252',
//     [HIGHLIGHT_BACKGROUND_VAR]:'#ffb364',
//     [CANVAS_MASK_BACKGROUND_VAR]:'#ff3db136',


//     [HEAD_HEIGHT]:'60px',
//     [ASIDE_WIDTH]:'200px',
//     [PANEL_WIDTH]:'300px',
//     [PADDING_1_VAR]:'4px',
//     [PADDING_2_VAR]:'8px',
//     [PADDING_3_VAR]:'12px',
//     [PADDING_4_VAR]:'16px',
//     [PADDING_5_VAR]:'20px',
//     [PADDING_6_VAR]:'24px',
//     [PADDING_7_VAR]:'28px',
//     [PADDING_8_VAR]:'32px',
//     [PADDING_9_VAR]:'36px',

//     [LINE_1_VAR]:'#3D7FFF',
//     [LINE_2_VAR]:'#505050'
// }object_row--hovered--3-taR
export default {
    [TEXT_COLOR_VAR]:'#333333',
    [NEGTIVE_TEXT_COLOR_VAR]:'#FFFFFF',
    [ACTIVE_TEXT_COLOR_VAR]:'#EFEFF0',
    [DISABLED_COLOR_VAR]:'#B3B3B3',
    [HIGHTLIGHT_COLOR_VAR]:'#ffb364',
    [HIGHTLIGHT_TEXT_COLOR_VAR]:'#4e4f50',


    [HIGHLIGHT_BORDER_COLOR_VAR]:'#18a0fb',
    [BOARDER_COLOR_VAR]:'#e5e5e5',

    [BACKGROUND_0_VAR]:'#F2F2F2',
    [BACKGROUND_1_VAR]:'#FFFFFF',
    [BACKGROUND_2_VAR]:'#FFFFFF',
    [BACKGROUND_3_VAR]:'#2C2C2C',
    [BACKGROUND_4_VAR]:'#E5E5E5',
    [BACKGROUND_5_VAR]:'#525252',
    [BACKGROUND_6_VAR]:'#888787',
    [HIGHLIGHT_BACKGROUND_VAR]:'#DAEBF7',
    [CANVAS_MASK_BACKGROUND_VAR]:'#ff3db136',
    [MOVABLE_MASK_BACKGROUND_VAR]:'#18a0fb10',
    [PRIMARY_BACKGROUND_VAR]:'#18a0fb',

    [HEAD_HEIGHT]:'52px',
    [ASIDE_WIDTH]:'200px',
    [PANEL_WIDTH]:'300px',
    [PADDING_1_VAR]:'4px',
    [PADDING_2_VAR]:'8px',
    [PADDING_3_VAR]:'12px',
    [PADDING_4_VAR]:'16px',
    [PADDING_5_VAR]:'20px',
    [PADDING_6_VAR]:'24px',
    [PADDING_7_VAR]:'28px',
    [PADDING_8_VAR]:'32px',
    [PADDING_9_VAR]:'36px',

    [LINE_1_VAR]:'#3D7FFF',
    [LINE_2_VAR]:'#505050'
}