


import {
    TEXT_COLOR_VAR,
    ACTIVE_TEXT_COLOR_VAR,
    HIGHTLIGHT_COLOR_VAR,
    BACKGROUND_0_VAR,
    BACKGROUND_1_VAR,
    BACKGROUND_2_VAR,
    BACKGROUND_3_VAR,
    BACKGROUND_4_VAR,
    BACKGROUND_5_VAR,
    HIGHLIGHT_BACKGROUND_VAR,
    HEAD_HEIGHT,
    ASIDE_WIDTH,
    PANEL_WIDTH,
    PADDING_1_VAR,
    PADDING_2_VAR,
    PADDING_3_VAR,
    PADDING_4_VAR,
    PADDING_5_VAR,
    PADDING_6_VAR,
    PADDING_7_VAR,
    PADDING_8_VAR,
    PADDING_9_VAR
} from './constant'

// export const TEXT_COLOR = '#83868E'
// export const ACTIVE_TEXT_COLOR = '#EFEFF0'
// export const BACKGROUND_1 = '#1A2233'
// export const BACKGROUND_2 = '#242C38'
// export const BACKGROUND_3 = '#2A3141'
// export const BACKGROUND_4 = '#333B4E'



export default {
    [TEXT_COLOR_VAR]:'#83868E',
    [ACTIVE_TEXT_COLOR_VAR]:'#EFEFF0',
    [HIGHTLIGHT_COLOR_VAR]:'#ffb364',

    [BACKGROUND_0_VAR]:'#090a0a',
    [BACKGROUND_1_VAR]:'#1A2233',
    [BACKGROUND_2_VAR]:'#242C38',
    [BACKGROUND_3_VAR]:'#2A3141',
    [BACKGROUND_4_VAR]:'#333B4E',
    [BACKGROUND_5_VAR]:'#525252',
    [HIGHLIGHT_BACKGROUND_VAR]:'#ffb364',
    // [TEXT_COLOR_VAR]:'#83868E',
    // [ACTIVE_TEXT_COLOR_VAR]:'#EFEFF0',
    // [BACKGROUND_1_VAR]:'#ffffff',
    // [BACKGROUND_2_VAR]:'#ffffff',
    // [BACKGROUND_3_VAR]:'#ffffff',
    // [BACKGROUND_4_VAR]:'#ffffff',

    [HEAD_HEIGHT]:'60px',
    [ASIDE_WIDTH]:'200px',
    [PANEL_WIDTH]:'300px',
    [PADDING_1_VAR]:'4px',
    [PADDING_2_VAR]:'8px',
    [PADDING_3_VAR]:'12px',
    [PADDING_4_VAR]:'16px',
    [PADDING_5_VAR]:'20px',
    [PADDING_6_VAR]:'24px',
    [PADDING_7_VAR]:'28px',
    [PADDING_8_VAR]:'32px',
    [PADDING_9_VAR]:'36px',
}