



// export const BACKGROUND = 'background'
// export const ACTIVE = 'active'




export const TEXT_COLOR_VAR = 'TEXT_COLOR'
export const ACTIVE_TEXT_COLOR_VAR = 'ACTIVE_TEXT_COLOR'
export const DISABLED_COLOR_VAR = 'DISABLED_COLOR'
export const HIGHTLIGHT_COLOR_VAR = 'HIGHTLIGHT_COLOR'
export const HIGHTLIGHT_TEXT_COLOR_VAR = 'HIGHTLIGHT_TEXT_COLOR'
export const BOARDER_COLOR_VAR = 'BOARDER_COLOR'


export const HIGHLIGHT_BORDER_COLOR_VAR = 'HIGHLIGHT_BORDER_COLOR'

export const BACKGROUND_0_VAR = 'BACKGROUND_0'
export const BACKGROUND_1_VAR = 'BACKGROUND_1'
export const BACKGROUND_2_VAR = 'BACKGROUND_2'
export const BACKGROUND_3_VAR = 'BACKGROUND_3'
export const BACKGROUND_4_VAR = 'BACKGROUND_4'
export const BACKGROUND_5_VAR = 'BACKGROUND_5'
export const HIGHLIGHT_BACKGROUND_VAR = 'HIGHLIGHT_BACKGROUND'
export const CANVAS_MASK_BACKGROUND_VAR = 'CANVAS_MASK_BACKGROUND'



export const HEAD_HEIGHT = 'HEAD_HEIGHT'
export const ASIDE_WIDTH = 'ASIDE_WIDTH'
export const PANEL_WIDTH = 'PANEL_WIDTH'


export const PADDING_1_VAR = 'PADDING_1'
export const PADDING_2_VAR = 'PADDING_2'
export const PADDING_3_VAR = 'PADDING_3'
export const PADDING_4_VAR = 'PADDING_4'
export const PADDING_5_VAR = 'PADDING_5'
export const PADDING_6_VAR = 'PADDING_6'
export const PADDING_7_VAR = 'PADDING_7'
export const PADDING_8_VAR = 'PADDING_8'
export const PADDING_9_VAR = 'PADDING_9'


export const LINE_1_VAR = 'LINE_1'
export const LINE_2_VAR = 'LINE_2'


