const FreeCanvas = require('../lib/index').default


FreeCanvas('canvas',{
    data:{
        isRoot:true,
        // isGroup:false,
        children:[{
            id:'111',
            name:'div',
            style:{
                width:'400px',
                height:'300px',
                backgroundColor:'#ff000055'
            },
            extra:{
                position:{
                    left:200,
                    top:10
                }
            },
            children:[
                {
                    id:'1111',
                    name:'div',
                    style:{
                        width:'200px',
                        height:'200px',
                        backgroundColor:'#00ff0055'
                    },
                    extra:{
                        position:{
                            left:10,
                            top:10
                        }
                    },
                    children:[
                        {
                            id:'11111',
                            name:'div',
                            style:{
                                width:'100px',
                                height:'100px',
                                backgroundColor:'#00ff3355'
                            },
                            extra:{
                                position:{
                                    left:20,
                                    top:20
                                }
                            },
                        }
                    ]
                } ,{
                    id:'1112',
                    name:'div',
                    style:{
                        left:'150',
                        top:'150',
                        width:'100px',
                        height:'100px',
                        backgroundColor:'#ffff0055'
                    },
                    extra:{
                        position:{
                            left:250,
                            top:150
                        }
                    }
                } 
            ]
        },{
            id:'112',
            name:'div',
            style:{
                width:'150px',
                height:'150px',
                backgroundColor:'#00000055'
            },
            extra:{
                position:{
                    left:400,
                    top:300
                }
            }
        },{
            id:'113',
            name:'div',
            style:{
                width:'150px',
                height:'150px',
                backgroundColor:'#00000055'
            },
            extra:{
                position:{
                    left:600,
                    top:400
                }
            }
        }]
    }
});