const FreeCanvas = require('../lib/index').default


FreeCanvas('canvas',{
    data:[{
        id:'111',
        tag:'div',
        attribute:{
            style:{
                width:'300px',
                height:'300px',
                left:'200px',
                top:'10px',
                backgroundColor:'red'
            }
        },
        children:[
            {
                id:'112',
                tag:'div',
                attribute:{
                    style:{
                        left:'10px',
                        top:'10px',
                        width:'200px',
                        height:'200px',
                        backgroundColor:'blue'
                    }
                }
            } ,{
                id:'113',
                tag:'div',
                attribute:{
                    style:{
                        left:'150',
                        top:'150',
                        width:'100px',
                        height:'100px',
                        backgroundColor:'yellow'
                    }
                }
            } 
        ]
    },{
        id:'112',
        tag:'div',
        attribute:{
            style:{
                left:'400px',
                top:'300px',
                width:'150px',
                height:'150px',
                backgroundColor:'black'
            }
        }
    }]
});