import FreeCanvas from '@pkg/free-canvas-core';
import {createView} from '@pkg/free-canvas-fusion-render';


const canvas = FreeCanvas('canvas',{
    createView,
    data:{
        isRoot:true,
        extra:{},
        // isGroup:false,
        children:[{
            id:'111',
            name:'div',
            style:{
                backgroundColor:'#ff000055'
            },
            extra:{
                position:{
                    left:200,
                    top:10,
                    width:400,
                    height:300,
                }
            },
            children:[
                {
                    id:'1111',
                    name:'div',
                    style:{
                        backgroundColor:'#00ff0055'
                    },
                    extra:{
                        position:{
                            left:10,
                            top:10,
                            width:200,
                            height:200,
                        }
                    },
                    children:[
                        {
                            id:'11111',
                            name:'div',
                            style:{
                                backgroundColor:'#00ff3355'
                            },
                            extra:{
                                position:{
                                    left:20,
                                    top:20,
                                    width:100,
                                    height:100,
                                }
                            },
                        }
                    ]
                } ,{
                    id:'1112',
                    name:'div',
                    style:{
                        backgroundColor:'#ffff0055'
                    },
                    extra:{
                        position:{
                            left:250,
                            top:150,
                            width:100,
                            height:100,
                        }
                    }
                } 
            ]
        },{
            id:'112',
            name:'div',
            style:{
                backgroundColor:'#00000055'
            },
            extra:{
                position:{
                    left:400,
                    top:300,
                    width:150,
                    height:150,
                }
            }
        },{
            id:'113',
            name:'div',
            style:{
                backgroundColor:'#00000055'
            },
            extra:{
                position:{
                    left:600,
                    top:400,
                    width:150,
                    height:150,
                }
            }
        }]
    }
});
//@ts-ignore
const {$$onCanvasLoaded} = window.top;
if($$onCanvasLoaded){
    $$onCanvasLoaded(canvas);
}